name: Ruff Checks

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-ruff:
    runs-on: ubuntu-20.04

    name: ruff tests
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install required system packages
        run: sudo apt-get update && sudo apt-get install libxmlsec1-dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Get pip cache dir
        id: pip-cache-dir
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip dependencies
        id: cache-dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/edx/development.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install required Python dependencies
        run: |
          # dev-requirements is needed because the linter will otherwise
          # trip over some dev-only things like django-debug-toolbar
          # (import debug_toolbar) that aren't in testing.txt.
          make dev-requirements
          # After all requirements are installed, check that they're consistent with each other
          pip check

      - name: Run quality tests
        run: |
          ruff check lms/djangoapps/ lms/envs/ lms/lib/ lms/tests.py \
            openedx/core/djangoapps/ openedx/core/djangolib/ openedx/core/lib/ openedx/core/tests/ \
            openedx/core/tests/ openedx/core/types/ openedx/features/ openedx/testing/ openedx/tests/ \
            cms common xmodule --preview

  # This job aggregates test results. It's the required check for branch protection.
  # https://github.com/marketplace/actions/alls-green#why
  # https://github.com/orgs/community/discussions/33579
  success:
    name: Ruff checks successful
    if: always()
    needs:
      - run-ruff
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        # uses: re-actors/alls-green@v1.2.1
        uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe
        with:
          jobs: ${{ toJSON(needs) }}
